/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as SkillsNewRouteImport } from './routes/skills.new'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as SkillsSlugEditRouteImport } from './routes/skills.$slug.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugEditRoute = SkillsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SkillsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/skills/$slug': typeof SkillsSlugRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/skills/': typeof SkillsIndexRoute
  '/skills/$slug/edit': typeof SkillsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/skills/$slug': typeof SkillsSlugRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/skills': typeof SkillsIndexRoute
  '/skills/$slug/edit': typeof SkillsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/skills/$slug': typeof SkillsSlugRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/skills/': typeof SkillsIndexRoute
  '/skills/$slug/edit': typeof SkillsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/skills/$slug'
    | '/skills/new'
    | '/skills/'
    | '/skills/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/skills/$slug'
    | '/skills/new'
    | '/skills'
    | '/skills/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/skills/$slug'
    | '/skills/new'
    | '/skills/'
    | '/skills/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SkillsSlugRoute: typeof SkillsSlugRouteWithChildren
  SkillsNewRoute: typeof SkillsNewRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug/edit': {
      id: '/skills/$slug/edit'
      path: '/edit'
      fullPath: '/skills/$slug/edit'
      preLoaderRoute: typeof SkillsSlugEditRouteImport
      parentRoute: typeof SkillsSlugRoute
    }
  }
}

interface SkillsSlugRouteChildren {
  SkillsSlugEditRoute: typeof SkillsSlugEditRoute
}

const SkillsSlugRouteChildren: SkillsSlugRouteChildren = {
  SkillsSlugEditRoute: SkillsSlugEditRoute,
}

const SkillsSlugRouteWithChildren = SkillsSlugRoute._addFileChildren(
  SkillsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminUsersRoute: AdminUsersRoute,
  SkillsSlugRoute: SkillsSlugRouteWithChildren,
  SkillsNewRoute: SkillsNewRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
